[package]
edition = "2021"
name = "smf-rust"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
human-sort = "0.2.2"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.2", default-features = false, features = ["napi4"] }
napi-derive = "2.9.3"
regex = "1.7.0"
sysinfo = "0.28.4"
walkdir = "2.3.2"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
